// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateTask(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateTask'](arg1, arg2, arg3, arg4);
}

export function CreateTasksBatch(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateTasksBatch'](arg1, arg2, arg3, arg4);
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function DisconnectBrowser() {
  return window['go']['main']['App']['DisconnectBrowser']();
}

export function GetBrowserInfo() {
  return window['go']['main']['App']['GetBrowserInfo']();
}

export function GetBrowserStatus() {
  return window['go']['main']['App']['GetBrowserStatus']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetQueueState() {
  return window['go']['main']['App']['GetQueueState']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetTask(arg1) {
  return window['go']['main']['App']['GetTask'](arg1);
}

export function GetTaskStats() {
  return window['go']['main']['App']['GetTaskStats']();
}

export function GetVideoData(arg1) {
  return window['go']['main']['App']['GetVideoData'](arg1);
}

export function LaunchBrowser() {
  return window['go']['main']['App']['LaunchBrowser']();
}

export function ListTasks(arg1) {
  return window['go']['main']['App']['ListTasks'](arg1);
}

export function PauseQueue() {
  return window['go']['main']['App']['PauseQueue']();
}

export function ResumeQueue() {
  return window['go']['main']['App']['ResumeQueue']();
}

export function SelectDirectory(arg1) {
  return window['go']['main']['App']['SelectDirectory'](arg1);
}

export function SelectFile(arg1) {
  return window['go']['main']['App']['SelectFile'](arg1);
}

export function StartQueue() {
  return window['go']['main']['App']['StartQueue']();
}

export function StopQueue() {
  return window['go']['main']['App']['StopQueue']();
}

export function UpdateSetting(arg1, arg2) {
  return window['go']['main']['App']['UpdateSetting'](arg1, arg2);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}

export function ValidateChromePath(arg1) {
  return window['go']['main']['App']['ValidateChromePath'](arg1);
}

export function ValidateDownloadFolder(arg1) {
  return window['go']['main']['App']['ValidateDownloadFolder'](arg1);
}

export function ValidateUserDataDir(arg1) {
  return window['go']['main']['App']['ValidateUserDataDir'](arg1);
}

export function WindowClose() {
  return window['go']['main']['App']['WindowClose']();
}

export function WindowMinimise() {
  return window['go']['main']['App']['WindowMinimise']();
}

export function WindowToggleMaximise() {
  return window['go']['main']['App']['WindowToggleMaximise']();
}
