// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';
import {chrome} from '../models';
import {config} from '../models';

export function CreateTask(arg1:string,arg2:string,arg3:string,arg4:number):Promise<database.Task>;

export function CreateTasksBatch(arg1:Array<string>,arg2:string,arg3:string,arg4:number):Promise<Array<database.Task>>;

export function DeleteTask(arg1:string):Promise<void>;

export function DisconnectBrowser():Promise<void>;

export function GetBrowserInfo():Promise<chrome.BrowserInfo>;

export function GetBrowserStatus():Promise<string>;

export function GetConfig():Promise<config.AppConfig>;

export function GetQueueState():Promise<string>;

export function GetSettings():Promise<Record<string, string>>;

export function GetTask(arg1:string):Promise<database.Task>;

export function GetTaskStats():Promise<database.TaskStats>;

export function GetVideoData(arg1:string):Promise<string>;

export function LaunchBrowser():Promise<void>;

export function ListTasks(arg1:database.TaskFilter):Promise<Array<database.Task>>;

export function PauseQueue():Promise<void>;

export function ResumeQueue():Promise<void>;

export function SelectDirectory(arg1:string):Promise<string>;

export function SelectFile(arg1:string):Promise<string>;

export function StartQueue():Promise<void>;

export function StopQueue():Promise<void>;

export function UpdateSetting(arg1:string,arg2:string):Promise<void>;

export function UpdateSettings(arg1:Record<string, string>):Promise<void>;

export function ValidateChromePath(arg1:string):Promise<string>;

export function ValidateDownloadFolder(arg1:string):Promise<string>;

export function ValidateUserDataDir(arg1:string):Promise<string>;

export function WindowClose():Promise<void>;

export function WindowMinimise():Promise<void>;

export function WindowToggleMaximise():Promise<void>;
